#+title:  Favorite Repository Index
#+subtitle: A distributed service architecture powered by nix and gRPC-haskell
#+author: Tristan de Cacqueray
#+date:   2021-04-24
#+export_file_name: ../README.md

* tl;dr
:PROPERTIES:
:CUSTOM_ID: tldr
:END:

This project implements a simple service named Favorite Repository Index (FRI).
The service let user registers by indexing their favorite repositories, then the service enable the user to perform full text search.
When multiple users use the service, it can display the most popular repository amongs the registered users.

The goal is to implement an incremental roadmap using architectural decision records ([[https://adr.github.io][ADR]]).

#+begin_src plantuml :file doc/architecture.png :eval yes
  title FRI architecture

  package "backend" {
    database "database" as Datastore
    collections "fri-api" as Api
    collections "fri-worker" as Worker
    cloud proxy as Proxy
  }
  actor user as User

  Api --> Datastore
  Api <--> Worker
  Proxy -> Api
  User --> Proxy
#+end_src

#+begin_src plantuml :file doc/sequence.png :eval yes
title FRI workflow
actor user as User
participant "fri-api" as Api
participant "fri-worker" as Worker
entity "GitHub"  as GH
database "database" as Db

User -> Api    : send github username
Api -> GH      : request favorites repos
User <- Api    : stream repos information
Api -> Db      : index repos
...
User -> Api    : send full text search
Api -> Db      : query index
User <- Api    : get result
...
Worker -> Api  : request last timestamp
Worker -> GH   : get repo updates
Worker -> Api  : send updates
Api -> Db      : index updates
#+end_src

* Motivation
:PROPERTIES:
:CUSTOM_ID: motivation
:END:

I introduced a purely functional and strongly typed component, named [[https://github.com/change-metrics/lentille][Lentille]], while working on adding task datas to the [[https://github.com/change-metrics/monocle][Monocle]] service.
I used Lentille to showcase a practical application of the Haskell language: performing data processing of the bugzilla API.
Then, I investigated how one could leverage this approach for the rest of the service, in particular, the web api and client which are written in Python and Javascript.

So my idea was to use an IDL such as OpenAPI or Protobuf to implement the next features while keeping the existing code in place.
Before working around the existing code base, I wanted to investigate using Haskell and gRPC in a greenfield project first.

I'm pretty satisfied with the result, and I'm eager to share my approach with you!

* The Challenge
:PROPERTIES:
:CUSTOM_ID: challenge
:END:

TODO: define the goal and the challenges of Monocle.

* Roadmap
:PROPERTIES:
:CUSTOM_ID: roadmap
:END:

> This roadmap is a work in progress.
Once the project reachs a desirable state, each step will be mapped to a standalone commit.

** Packages Management
:PROPERTIES:
:CUSTOM_ID: packages-management
:END:

[[./doc/adr/choice-of-packages-manager.md][Choice of package manager record]]

- A shell environment with development tools installed:

#+begin_src
$ nix-shell --pure
[nix-shell]$ which strace
/nix/store/6yf85zvdchma8khwa7gl4ng6h3b4yr9n-strace-5.11/bin/strace
#+end_src

- Ready to use command to operate the service:

#+begin_src
$ fri-start
[+] Starting the database...
[+] Start the api...
#+end_src

** Database
:PROPERTIES:
:CUSTOM_ID: database
:END:

[[https://github.com/change-metrics/monocle/blob/master/doc/adr/0002-choice-of-elasticsearch.md][Choice of elasticsearch record]]

- elasticsearch service deployment:

#+begin_src
$ elk-start
Starting the database...

$ curl localhost:9242
{ "name": "fri", ..., "tagline" : "You Know, for Search"}

$ elk-stop
Stoping the database...

$ elk-destroy
Deleting the database...
#+end_src

** Interfaces Definition
:PROPERTIES:
:CUSTOM_ID: interfaces-definition
:END:

[[https://github.com/change-metrics/monocle/blob/master/doc/adr/0010-choice-of-protobuf.md][Choice of protobuf record]]

- protobuf definitions of the api: [[./protos/fri.proto][fri.proto]]

- haskell, javascript and python code generation:

#+begin_src
$ protobuf-codegen
Haskell bindings:
compile-proto-file --proto protos/fri.proto --out src/

Python bindings:
python3 -m grpc_tools.protoc -Iprotos --python_out=python/ --grpc_python_out=python/ fri.proto

Javascript bindings:
protoc -I=protos fri.proto --js_out=import_style=commonjs:javascript/src/ --grpc-web_out=import_style=commonjs,mode=grpcwebtext:javascript/src/
#+end_src

** Api Service
:PROPERTIES:
:CUSTOM_ID: api-structure
:END:

[[https://github.com/change-metrics/lentille/blob/main/doc/adr/0002-choice-of-language.md][Choice of language record]]

- A package set with relude version 1.0:

#+begin_src
$ ghc-pkg list relude
    relude-1.0.0.1
#+end_Src

- A REPL:

#+begin_src
$ cabal repl -O0
Ok, five modules loaded.
λ> import Api
λ> :type Api.run
Api.run :: Int -> IO ()
#+end_src

- A CLI to start the service:

#+begin_src
$ cabal run fri-api -- --elk-url http://localhost:9242 --port 8042
fri-api running on :8042
#+end_src

** GitHub Queries
:PROPERTIES:
:CUSTOM_ID: github-queries
:END:

- A haskell module to define crawler functions ([[./src/Fri/GitHub.hs][Fri.GitHub]]):

#+begin_src haskell
getFavorites :: MonadIO m => UserName -> Stream (Of RepoInitial) m ()
#+end_src

- REPL tutorial:

#+begin_src haskell
λ> S.print $ Fri.GitHub.getFavorites (UserName "TristanCacqueray")
RepoInitial {riName = RepoName "haskellfoundation/matchmaker", riDescription = Just (RepoDescription {unDesc = "Find your open-soulmate <\128156>"})}
RepoInitial {riName = RepoName "Gabriel439/grace", riDescription = Just (RepoDescription {unDesc = "A ready-to-fork interpreted, typed, and functional language"})}
...
#+end_src


** Database Queries
:PROPERTIES:
:CUSTOM_ID: database-queries
:END:

- A haskell module to define elasticsearch query ([[./src/Fri/Query.hs][Fri.Query]]):

#+begin_src haskell
addRepos :: (MonadThrow m, MonadIO m) => V.Vector RepoInitial -> Query m ()
#+end_src

- REPL tutorial:

#+begin_src haskell
λ> newClient "http://localhost:9242" >>= flip runQuery getIndices
[IndexName "fri.0"]
#+end_src

** Worker API
:PROPERTIES:
:CUSTOM_ID: client-api
:END:

- A haskell module to define worker ([[./src/Fri/Worker.hs][Fri.Worker]]):

#+begin_src haskell
-- TODO
indexTags :: undefined
#+end_src

- REPL tutorial:

#+begin_src haskell
λ> TODO
#+end_src

- A CLI to start the service:

#+begin_src
$ cabal run fri-worker -- --api-endpoint localhost:8042
#+end_src


** Client API
:PROPERTIES:
:CUSTOM_ID: client-api
:END:

- TODO: API implementation

- REPL tutorial:
#+begin_src haskell
λ> TODO
#+end_src

** Proxy
:PROPERTIES:
:CUSTOM_ID: proxy
:END:

[[https://github.com/change-metrics/monocle/issues/345][Choice of envoyproxy record]]

- envoy service deployment:

#+begin_src
$ envoy -c conf/envoy.yaml
starting main dispatch loop
#+end_src

** User Interface
:PROPERTIES:
:CUSTOM_ID: user-interface
:END:

- Live development server:

#+begin_src
$ cd javascript; pnpm start
> react-scripts start
#+end_Src

** Left Over
:PROPERTIES:
:CUSTOM_ID: left-over
:END:
- Authentication (openid, jwt, ...).
- Standalone cli (compose service function in a TUI).
- Distribution (container, vm, ansible, ...).
- Service auto scaling.
- CI with cachix.
