# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fri/services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fri import messages_pb2 as fri_dot_messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fri/services.proto',
  package='frirpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x66ri/services.proto\x12\x06\x66rirpc\x1a\x12\x66ri/messages.proto2\x85\x01\n\x07Service\x12?\n\x08Register\x12\x16.fripb.RegisterRequest\x1a\x17.fripb.RegisterResponse\"\x00\x30\x01\x12\x39\n\x06Search\x12\x14.fripb.SearchRequest\x1a\x15.fripb.SearchResponse\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[fri_dot_messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SERVICE = _descriptor.ServiceDescriptor(
  name='Service',
  full_name='frirpc.Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=51,
  serialized_end=184,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='frirpc.Service.Register',
    index=0,
    containing_service=None,
    input_type=fri_dot_messages__pb2._REGISTERREQUEST,
    output_type=fri_dot_messages__pb2._REGISTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='frirpc.Service.Search',
    index=1,
    containing_service=None,
    input_type=fri_dot_messages__pb2._SEARCHREQUEST,
    output_type=fri_dot_messages__pb2._SEARCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['Service'] = _SERVICE

# @@protoc_insertion_point(module_scope)
